org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Project
mod_version=0.1.0
maven_group=com.stormcph
archives_base_name=easygui
enabled_platforms=fabric,neoforge

# Minecraft
minecraft_version=1.21.1

# Dependencies
architectury_api_version=13.0.8
fabric_loader_version=0.19.3
fabric_api_version=0.116.12+1.21.1
neoforge_version=21.1.233
